### ISSUE TITLE
pull xaiverniu/cloudreve:arm64v8报错

### ISSUE THREAD

**Issue by 0x01x0** [xavier-niu/cloudreve-docker#1]
报错：Error response from daemon: pull access denied for xaiverniu/cloudreve, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

https://blog.csdn.net/kuangay/article/details/80635155
是这个帖子说的问题嘛？

**Comment by justxuewei** [comment]
我这边没有任何问题，而且镜像是公开的不存在登陆的问题，请复制并执行`docker pull xavierniu/cloudreve:arm64v8`尝试一下。

**Comment by 0x01x0** [comment]
> 我这边没有任何问题，而且镜像是公开的不存在登陆的问题，请复制并执行`docker pull xavierniu/cloudreve:arm64v8`尝试一下。

不停的docker pull几十次 终于成功了 不知道啥问题 应该不是网络问题 因为我pull latest是没问题的

**Comment by justxuewei** [comment]
> > 我这边没有任何问题，而且镜像是公开的不存在登陆的问题，请复制并执行`docker pull xavierniu/cloudreve:arm64v8`尝试一下。
> 
> 不停的docker pull几十次 终于成功了 不知道啥问题 应该不是网络问题 因为我pull latest是没问题的

第一 根据标题是xavierniu不是xaiverniu
第二 如果多次不成功可能是网络问题，可以考虑更换国内源
