### ISSUE TITLE
cloudreve-docker，运行后，显示不正常。

### ISSUE THREAD

**Issue by jy3344511** [xavier-niu/cloudreve-docker#10]
虚拟机跑openwrt x64，运行cloudreve-docker，可以进入登录界面，有账号、密码的那种。回到本地openwrt arm64，运行cloudreve-docker，可以进入cloudreve的界面，不是完全打不开那种，但是啥都不显示，这怎么搞啊？？？？

![image](https://user-images.githubusercontent.com/49992475/81708043-921a5200-94a3-11ea-9cd8-95d62694ecea.png)

![02](https://user-images.githubusercontent.com/49992475/81708082-97779c80-94a3-11ea-8a30-97e918b76e66.jpg)

**Comment by justxuewei** [comment]
删除浏览器缓存试试

**Comment by jy3344511** [comment]
> 删除浏览器缓存试试

可以了。
