### ISSUE TITLE
cd无法上传大文件

### ISSUE THREAD

**Issue by liubangjain** [xavier-niu/cloudreve-docker#13]
大佬你好
         我用群晖运行此docker，运行的是OC模式，存储策略用的是世纪互联的onedrive；可以上传比较小的文件，例如txt文件或者几兆的exe文件，但是上传大概40-50m的rar文件，就提示上传失败，而我去到OneDrive的网页版看到该文件是上传成功的，但是在cloudreve上提示上传失败，而且不显示。conf.ini文件没有任何数据。请问是什么原因？请问怎么解决？期待你的回复。

**Comment by xavier-niu** [comment]
这类问题不是镜像导致的，请去cloudreve官方repo提issue，谢谢。

**Comment by xavier-niu** [comment]
提供一个思路，如果你使用nginx作为反代服务器，里面有一个设置是限制上传大小的，具体我忘记了。

**Comment by liubangjain** [comment]
还没设置反向代理，现在就是用192段局域网来访问。

**Comment by xavier-niu** [comment]
那就去官方repo问问吧，可能是程序bug。

**Comment by liubangjain** [comment]
1
在设置存储策略od的设置
是否限制上传的单文件大小？
限制
不限制

**Comment by liubangjain** [comment]
好的

**Comment by liubangjain** [comment]
henrywu19359 commented 2 minutes ago
看上去你需要检查一下Nginx的MAX-BODY-SIZE的配置是否限制了上传大小。
有网友这样回复，请问此docker怎么检查？

**Comment by xavier-niu** [comment]
这个镜像是完全纯净的，没有使用nginx。

**Comment by liubangjain** [comment]
我试了国际版和世纪互联版的OD情况都一样。

**Comment by liubangjain** [comment]
大佬，请问怎么设置https的形式来登陆啊 ？

**Comment by xavier-niu** [comment]
这些问题都不属于镜像问题，你可以参考dockerfile，我做的工作仅仅是重新编译了一次源码，所以你需要在cloudreve的官方支援地址发送你的疑问，该issue将被锁定。
