### ISSUE TITLE
webdav无法使用

### ISSUE THREAD

**Issue by 0xuhe** [xavier-niu/cloudreve-docker#16]
caddy的反向代理没有/dav的相关配置

**Comment by justxuewei** [comment]
有关`/dav`的配置是指？

**Comment by 0xuhe** [comment]
webdav没法用, 是不是因为/dav这个在caddy里面没有做路由配置

**Comment by justxuewei** [comment]
我查看了cloudreve的文档，并没有对webdav单独配置的表述。而且本仓库是docker镜像仓库，README中的教程仅仅是对新手进行一些启发和帮助，恕不专门研究这方面的问题。如果您有不错的建议，请提PR。
