### ISSUE TITLE
cloudreve/conf.ini not work

### ISSUE THREAD

**Issue by cheninaisino** [xavier-niu/cloudreve-docker#18]
xaiverniu/cloudreve:latest for linux/amd64
已经升级到V3.1.1
新特性支持原生https
但是docker版目前似乎endpoint.sh没把 -c conf.ini参数放进去

**Comment by justxuewei** [comment]
今晚之前会更新unstable版本，请耐心等待。

**Comment by justxuewei** [comment]
我重新看了一下，配置可以更改，你按照教程修改`/dockercnf/cloudreve/conf.ini`中的内容试一下。

**Comment by cheninaisino** [comment]
其实并不是这里的问题，是镜像中entrypoint.sh启动cloudreve-main程序不执行 -c conf.ini参数
改那部分再配conf.ini就行，我已经自己改好了😁



---Original---
From: "XavierNiu"



 
等等，默认配置可以更改，你按照教程修改/dockercnf/cloudreve/conf.ini试一下。

**Comment by justxuewei** [comment]
需要修改entrypoint文件吗？您可否提供一下解决方案，谢谢。

**Comment by cheninaisino** [comment]
其实就是在entrypoint.sh里加入cloudreve的运行参数就行了
然后conf.ini配置文件就起作用了，需要https就把证书路径-v到指定路径去。
见图







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"XavierNiu"<notifications@github.com&gt;;
发送时间:&nbsp;Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xavier-niu/cloudreve-docker] cloudreve/conf.ini not work (#18)





 
需要修改entrypoint文件吗？您可否提供一下解决方案，谢谢。

**Comment by xavier-niu** [comment]
您的意思是在entrypoint中的最后一行改为`cloudreve-main -c /cloudreve/conf.ini`?

**Comment by cheninaisino** [comment]
是的，这样启动就会加载配置文件conf.ini，这个文件你其实也用-v参数引入文件了，但是不加-c /cloudreve/conf.ini默认主文件执行不会去读配置文件信息




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "XavierNiu"<notifications@github.com&gt;; 
发送时间: 2020年7月3日(星期五) 上午8:50
收件人: "xavier-niu/cloudreve-docker"<cloudreve-docker@noreply.github.com&gt;; 
抄送: Author"<author@noreply.github.com&gt;; 
主题: Re: [xavier-niu/cloudreve-docker] cloudreve/conf.ini not work (#18)





 
您的意思是在entrypoint中的最后一行改为cloudreve-main -c /cloudreve/conf.ini?

**Comment by justxuewei** [comment]
感谢反馈，目前我已经在develop分支提交了修改，约10分钟后可以尝试在docker hub中拉取最新的`unstable`分支，主分支将于cloudreve下一个版本发布后合并。
