### ISSUE TITLE
Download almost disconnected, very slow

### ISSUE THREAD

**Issue by haododo** [xavier-niu/cloudreve-docker#19]
离线下载几个G的文件，下到80%左右就几乎断线了，而且idm重连再也连不上，排除vps的问题（因为之前用nextcloud没这现象），请问这是跟设置有关吗？还有添加离线下载后总是要选择下载位置，有没有办法设置好位置就不用选择直接就下到那个地方的。

**Comment by justxuewei** [comment]
该项目为cloudreve镜像开源项目，您提到的问题为cloudreve本身问题，请移步至cloudreve官方仓库提出issue，寻求解决方法，谢谢。
