### ISSUE TITLE
使用基础镜像的时区好像并没有修改成功

### ISSUE THREAD

**Issue by liangjihua** [xavier-niu/cloudreve-docker#2]
镜像里面使用的还是UTC时间，不是东八区的时间：
![image](https://user-images.githubusercontent.com/35123083/79062320-d6aba580-7ccb-11ea-81e1-176aeb79e7c5.png)

**Comment by justxuewei** [comment]
请问你用的是哪个架构的cloudreve镜像？

**Comment by liangjihua** [comment]
linux/amd64

**Comment by justxuewei** [comment]
目前已修复该问题，请等待GitHub Action的`latest-and-amd64`运行结束使用`unstable`tag测试，大概10分钟左右。
