### ISSUE TITLE
使用Docker Compose方式部署完成后，管理员帐号和密码在哪里？

### ISSUE THREAD

**Issue by gray0128** [xavier-niu/cloudreve-docker#20]
请问使用Docker Compose方式部署完成后，管理员帐号和密码在哪里？

**Comment by justxuewei** [comment]
同docker run的方式，都是在日志中看。

**Comment by gray0128** [comment]
> 同docker run的方式，都是在日志中看。

谢谢！
我试过docker logs -f cloudreve，结果是Error: No such container: cloudreve
应该跟我的文件名有关，运行docker-compose up -d后，显示的是
root_cloudreve_1 is up-to-date
root_aria2_1 is up-to-date
root_caddy_1 is up-to-date
现在用docker logs -f root_cloudreve_1找到帐号信息了

**Comment by justxuewei** [comment]
是的，你需要根据你实际的容器名称来确定最终的命令。
