### ISSUE TITLE
离线下载文件转存失败

### ISSUE THREAD

**Issue by gray0128** [xavier-niu/cloudreve-docker#21]
感谢作者！
请问离线下载文件转存失败是什么原因？
另外失败原因无法完整显示，是不是要去log日志中查找？

![转存失败](https://bobocai-1256132207.cos.ap-chengdu.myqcloud.com/0200806101850.png)

**Comment by gray0128** [comment]
看到完整提示了：文件转存失败：PUT https://yunpan-1256132207.cos.ap-shanghai.myqcloud.com/uploads%2F2020%2F08%2F06%2F9UVFC0DB_mysql-installer-community-8.0.19.0.msi: 400 UserNetworkTooSlow(Message: User network is too slow.,

**Comment by justxuewei** [comment]
你好，这个问题不属于docker镜像问题，请移步至cloudreve官方仓库提问。

**Comment by xavier-niu** [comment]
FYI 我看到有人遇到了和你一样的问题 https://github.com/cloudreve/Cloudreve/issues/516
