### ISSUE TITLE
建议在 Readme 的安装指令中添加对 Cloudreve 的 Temp 目录映射参数

### ISSUE THREAD

**Issue by LamGC** [xavier-niu/cloudreve-docker#22]
建议在 Readme 中添加对 `/cloudreve/temp` 路径的映射参数，以防因缓存过多且容器所在磁盘空间不足导致相关操作失败（比如对非本机存储策略的多个大文件进行打包下载可能会导致服务器磁盘空间大量消耗而无法转移到缓存盘，非常恐怖）。

**Comment by justxuewei** [comment]
感谢提议，因为这个readme是作为新手起步使用的，所以会尽量做到精简，省略不必要的内容。这篇issue将作为不错的查找此类问题的参考，感谢！
