### ISSUE TITLE
docker镜像怎么设置临时下载目录呢？

### ISSUE THREAD

**Issue by gaoxianglyx** [xavier-niu/cloudreve-docker#24]
![image](https://user-images.githubusercontent.com/14159090/92387411-0e6a2c80-f148-11ea-8a08-e513cd6a0a61.png)
我尝试这里的绝对路径，好像是相对于镜像的路径的，我需要临时下载目录也在我的硬盘上啊，不然装不下

请问需要怎么设置呢？

**Comment by justxuewei** [comment]
就是会映射到硬盘上的，麻烦您提供aira2和cloudreve的运行命令。

**Comment by gaoxianglyx** [comment]
感谢回复，
docker 运行命令：`docker run -d   --name cloudreve   -e PUID=0   -e PGID=0   -e TZ="Asia/Shanghai"   -p 5212:5212   --restart=unless-stopped   -v /mnts/share:/cloudreve/uploads   -v /dockercnf/cloudreve/conf.ini:/cloudreve/conf.ini   -v /dockercnf/cloudreve/cloudreve.db:/cloudreve/cloudreve.db   xavierniu/cloudreve`

aria2运行命令
`docker run -d     --name aria2     --restart unless-stopped     --log-opt max-size=1m     -e PUID=0     -e PGID=0     -e RPC_SECRET=naive     -p 6800:6800     -p 6888:6888 -p 6888:6888/udp     -v /dockercnf/aria2/config:/config     -v /mnts/share:/downloads     p3terx/aria2-pro`


/mnts/share是我挂载硬盘的路径，但是临时下载目录是相对于/var/lib/docker/overlay2/的，是镜像文件的位置

这个空间不够我的下载需求，就卡在这里了

**Comment by justxuewei** [comment]
你的cloudreve似乎没有挂载`/downloads`文件夹

**Comment by gaoxianglyx** [comment]
我手动上传文件，是存在mnts/share下的，这是否说明cloudreve是挂载上的
![image](https://user-images.githubusercontent.com/14159090/92389465-b2a1a280-f14b-11ea-9a0c-e5c9451ccfa0.png)

**Comment by gaoxianglyx** [comment]
你临时下载的目录也是相对与downloads的？

**Comment by justxuewei** [comment]
> 你临时下载的目录也是相对与downloads的？

我不是很明白您说的相对目录是什么意思？可否相对目录的举个例子？

**Comment by gaoxianglyx** [comment]
> > 你临时下载的目录也是相对与downloads的？
> 
> 我不是很明白您说的相对目录是什么意思？可否相对目录的举个例子？

不好意思，我复述一下我的问题
我的环境是arm64

我发现aria2的临时下载目录，是基于docker镜像的目录，我希望临时下载目录，能到我的根目录，我挂载了硬盘。

我想问一下这个是我配置有误，还是本就是这个逻辑呢？

如果本就是这个逻辑，是否有办法临时下载到根目录呢？

**Comment by justxuewei** [comment]
可以尝试使用如下命令运行Cloudreve

```bash
docker run -d --name cloudreve \
  -e PUID=0 -e PGID=0 \
  -e TZ="Asia/Shanghai" \
  -p 5212:5212 --restart=unless-stopped \
  -v /mnts/share:/cloudreve/uploads \
  -v /dockercnf/cloudreve/conf.ini:/cloudreve/conf.ini \
  -v /mnts/share:/downloads \
  -v /dockercnf/cloudreve/cloudreve.db:/cloudreve/cloudreve.db \
  xavierniu/cloudreve
```

Aria2的保持不变

然后在Cloudreve的临时下载目录设置`\downloads`，这样你的下载项可以在`/mnts/share`中查看。

**Comment by gaoxianglyx** [comment]
> 可以尝试使用如下命令运行Cloudreve
> 
> ```shell
> docker run -d --name cloudreve \
>   -e PUID=0 -e PGID=0 \
>   -e TZ="Asia/Shanghai" \
>   -p 5212:5212 --restart=unless-stopped \
>   -v /mnts/share:/cloudreve/uploads \
>   -v /dockercnf/cloudreve/conf.ini:/cloudreve/conf.ini \
>   -v /mnts/share:/downloads \
>   -v /dockercnf/cloudreve/cloudreve.db:/cloudreve/cloudreve.db \
>   xavierniu/cloudreve
> ```
> 
> Aria2的保持不变
> 
> 然后在Cloudreve的临时下载目录设置`\downloads`，这样你的下载项可以在`/mnts/share`中查看。

谢谢，我刚尝试了一下，没有修改cloudreve的启动命令，临时目录设置为/downloads，确实下载到了挂载里面
文件下载完成后报了个错：
`文件转存失败：open /downloads/aria2/1599532184239160545/Mulan.2020.1080p.WEBRip.x264-RARBG/Subs/9_Spanish.srt: no such file or directory`

这是下载完成后要转存到正式目录报错的吧？

**Comment by justxuewei** [comment]
你必须要修改cloudreve的docker启动命令，否则下载目录是不存在的。

**Comment by gaoxianglyx** [comment]
可以了，感谢
