### ISSUE TITLE
有些问题想请教

### ISSUE THREAD

**Issue by billy74** [xavier-niu/cloudreve-docker#25]
首先感谢大神的付出，辛苦维护
我是使用群辉Docker运行的，Docker小白不太会用
问题：
1.如何运行aria2啊
2.cloudreve本地策略，获取的直连仍然是api方式获取的带sing参数的地址
3.使用又拍存储策略上传成功，网页却不显示文件哦

不知道是哪里的问题，是不是我映射的目录权限问题啊？有QQ群么 方便大家一起讨论

**Comment by justxuewei** [comment]
1. aria2的运行方式我已经在文档中说的很清楚了，请仔细看一下文档。
2 & 3. 这个问题大概率是cloudreve的问题，请移步至cloudreve官方仓库提交issue。

QQ群暂时不提供，可以至cloudreve官方tg讨论，谢谢。
