### ISSUE TITLE
给点命令都是什么，换行，不然就是报字符错误

### ISSUE THREAD

**Issue by xiguafz** [xavier-niu/cloudreve-docker#27]
![image](https://user-images.githubusercontent.com/62539036/97381021-2e75cb00-1903-11eb-83f0-f9bd55200ab2.png)

docker: invalid reference format.

**Comment by justxuewei** [comment]
我没太明白标题是什么意思

**Comment by xiguafz** [comment]
> 我没太明白标题是什么意思

我说你给的命令，复制黏贴都是换行的。符号有问题吧

**Comment by justxuewei** [comment]
没有问题，后面有`\`控制换行。
