### ISSUE TITLE
docker-compose up -d 报错

### ISSUE THREAD

**Issue by ipme** [xavier-niu/cloudreve-docker#32]
`root@Ko-1:~# docker-compose up -d
WARNING: The CLOUDREVE_AVATAR_PATH variable is not set. Defaulting to a blank string.
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
root_aria2_1 is up-to-date
root_caddy_1 is up-to-date
Creating root_cloudreve_1 ... error

ERROR: for root_cloudreve_1  Cannot create container for service cloudreve: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for cloudreve  Cannot create container for service cloudreve: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.
`
docker compose 这里面的目录 怎么不用 ${PWD} 
这样写不是更好吗?
我启动不了..启动就报错..

**Comment by justxuewei** [comment]
是环境变量出问题了，我已经在Dev分支中修改了。但是请注意，代理服务器也由Caddy换成了Nginx，可能需要你重新完整的执行整个过程。

**Comment by justxuewei** [comment]
另外要注意的是，需要将wget连接从`https://raw.githubusercontent.com/xavier-niu/cloudreve-docker/master/xxx`改为`https://raw.githubusercontent.com/xavier-niu/cloudreve-docker/develop/xxx`
