### ISSUE TITLE
Docker Hub 文档问题!

### ISSUE THREAD

**Issue by vfiee** [xavier-niu/cloudreve-docker#33]
先贴出来文档: https://hub.docker.com/r/xavierniu/cloudreve

Docker Hub中镜像的地址和github中描述的镜像地址不一样(在github的问题上搜到的),相信有很多和我一样的都是pull失败,然后来github 看的,
看到麻烦修改一下

Docker hub镜像描述:  xaiverniu/cloudreve:arm64v8
实际真是的镜像: xavierniu/cloudreve:arm64v8

**Comment by vfiee** [comment]
> 先贴出来文档: https://hub.docker.com/r/xavierniu/cloudreve
> 
> Docker Hub中镜像的地址和github中描述的镜像地址不一样(在github的问题上搜到的),相信有很多和我一样的都是pull失败,然后来github 看的,
> 看到麻烦修改一下
> 
> Docker hub镜像描述: xaiverniu/cloudreve:arm64v8
> 实际真是的镜像: xavierniu/cloudreve:arm64v8

字母 i 右移

**Comment by justxuewei** [comment]
感谢指正，出错的位置不是核心代码区影响不大，下个大版本时会更新。
