### ISSUE TITLE
有没有使用 traefik 作为 web 服务器的想法？

### ISSUE THREAD

**Issue by expoli** [xavier-niu/cloudreve-docker#34]
https://doc.traefik.io/traefik/https/acme/

1. traefik 原生支持docker的服务发现、不需要像nginx那样需要手动配置
2. 只需要添加一个 label 就可以直接启用 Let's Encrypt 免费证书颁发
3. 简单易用

如果可以的话、我可以提供一个 traefik 使用的 compose 文件

**Comment by justxuewei** [comment]
感谢，请PR一个Readme，可以以外链的形式添加进去。但是主要还是使用Nginx作为服务器，一方面是Nginx是一个比较通用的软件，在时间上得到了验证，另一方面是相对来说配置选项升级平稳，不会出现配置文件完全不可用的情况。
