### ISSUE TITLE
无法解析配置文件 '/cloudreve/conf.ini':

### ISSUE THREAD

**Issue by pingpingpang001** [xavier-niu/cloudreve-docker#37]
docker run -d   \
    --name cloudreve  \
    -e PUID=1001 \
    -e PGID=100 \
    -e TZ="Asia/Shanghai"  \
    --restart=unless-stopped  \
    -v /srv/dev-disk-by-label-hgst/cloudrevedata/uploads:/cloudreve/uploads  \
    -v /srv/dev-disk-by-label-hgst/cloudrevedata/temp:/downloads  \
    -v /srv/dev-disk-by-label-hgst/cloudreve/configs/conf.ini:/cloudreve/conf.ini  \
    -v /srv/dev-disk-by-label-hgst/cloudreve/configs/cloudreve.db:/cloudreve/cloudreve.db  \
    -v /srv/dev-disk-by-label-hgst/cloudrevedata/avatar:/cloudreve/avatar  \
    xavierniu/cloudreve

运行日志如下：
[Panic]   2021-03-22 14:51:37 无法解析配置文件 '/cloudreve/conf.ini': BOM: read /cloudreve/conf.ini: is a directory
panic: 无法解析配置文件 '/cloudreve/conf.ini': BOM: read /cloudreve/conf.ini: is a directory

goroutine 1 [running]:
github.com/cloudreve/Cloudreve/v3/pkg/util.(*Logger).Panic(0xc0002ac860, 0x117813b, 0x21, 0xc0005bfac0, 0x2, 0x2)
	/ProjectCloudreve/Cloudreve/pkg/util/logger.go:74 +0xe5
github.com/cloudreve/Cloudreve/v3/pkg/conf.Init(0x7ffe74e4ff16, 0x13)
	/ProjectCloudreve/Cloudreve/pkg/conf/conf.go:121 +0x1de
github.com/cloudreve/Cloudreve/v3/bootstrap.Init(0x7ffe74e4ff16, 0x13)
	/ProjectCloudreve/Cloudreve/bootstrap/init.go:18 +0x3e
main.init.0()
	/ProjectCloudreve/Cloudreve/main.go:23 +0x205

运行环境OMV5 
确认已经创建conf.ini和cloudreve.db文件

请问这个问题如何解决

**Comment by justxuewei** [comment]
你在容器启动前需要执行

```
mkdir -p /dockercnf/cloudreve \
	&& touch /dockercnf/cloudreve/conf.ini \
	&& touch /dockercnf/cloudreve/cloudreve.db
```

请仔细按照教程来操作。
