### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by wuge0** [xavier-niu/cloudreve-docker#42]
[root@kk ~]# --restart=unless-stopped \
> -v <PATH TO UPLOADS>:/cloudreve/uploads \
> -v <PATH TO conf.ini>:/cloudreve/conf.ini \
> -v <PATH TO cloudreve.db>:/cloudreve/cloudreve.db \
> -v <PATH TO avatar>:/cloudreve/avatar \
> xavierniu/cloudreve
-bash: PATH: No such file or directory

**Comment by justxuewei** [comment]
请复制完整命令

**Comment by wuge0** [comment]
复制的是完整命令 最后提示 -bash: PATH: No such file or directory

**Comment by justxuewei** [comment]
> [root@kk ~]# --restart=unless-stopped \
> 
> > -v :/cloudreve/uploads 
> > -v :/cloudreve/conf.ini 
> > -v :/cloudreve/cloudreve.db 
> > -v :/cloudreve/avatar 
> > xavierniu/cloudreve
> > -bash: PATH: No such file or directory

请问完整命令是以--restart开头的吗？

**Comment by wuge0** [comment]
[root@kk ~]# id root
uid=0(root) gid=0(root) groups=0(root)
[root@kk ~]# mkdir -p /dockercnf/cloudreve \
> .&& touch /dockercnf/cloudreve/conf.ini \
> .&& touch /dockercnf/cloudreve/cloudreve.db
[root@kk ~]# docker run -d \
[root@kk ~]# docker run -d \
> --name cloudreve \
> -e PUID=0 \
> -e PGID=0 \
> -e TZ="Asia/Shanghai" \
> -p 5212:5212 \ 
 TO avatar>:/cloudreve/avatar \docker: invalid reference format.
See 'docker run --help'.
[root@kk ~]# --restart=unless-stopped \
> -v <PATH TO UPLOADS>:/cloudreve/uploads \
> -v <PATH TO conf.ini>:/cloudreve/conf.ini \
> -v <PATH TO cloudreve.db>:/cloudreve/cloudreve.db \
> -v <PATH TO avatar>:/cloudreve/avatar \
> xavierniu/cloudreve
-bash: PATH: No such file or directory
[root@kk ~]#

**Comment by justxuewei** [comment]
请使用code block(```)包裹代码

**Comment by wuge0** [comment]
> 请使用code block(```)包裹代码

如何使用

**Comment by justxuewei** [comment]
https://www.jianshu.com/p/65ab196bef04

**Comment by wuge0** [comment]
不好意思啊感觉看不懂
可以简单一点吗

**Comment by justxuewei** [comment]
目前这个问题应该是你的命令输入不正确导致的，不属于bug。这里的Issue讨论的是cloudreve-docker的bug或者改进的问题，不负责基础使用方面的答疑工作。关于你的问题，请咨询身边了解Linux或者Docker的人。

**Comment by wuge0** [comment]
Docker Run方式运行
OC
预创建Cloudreve的数据库和配置文件，这里以/dockercnf/cloudreve为cloudreve配置目录。

mkdir -p /dockercnf/cloudreve \
	&& touch /dockercnf/cloudreve/conf.ini \
	&& touch /dockercnf/cloudreve/cloudreve.db
启动容器

docker run -d \
  --name cloudreve \
  -e PUID=1000 \ # optional
  -e PGID=1000 \ # optional
  -e TZ="Asia/Shanghai" \ # optional
  -p 5212:5212 \ 
  --restart=unless-stopped \
  -v <PATH TO UPLOADS>:/cloudreve/uploads \
  -v <PATH TO conf.ini>:/cloudreve/conf.ini \
  -v <PATH TO cloudreve.db>:/cloudreve/cloudreve.db \
  -v <PATH TO avatar>:/cloudreve/avatar \
  xavierniu/cloudreve

我是按照这个一行行复制的
请问我哪行代码输入错误了？

**Comment by justxuewei** [comment]
需要去掉` # optional`（包括#前面的空格），以及有些行的`\`没有复制

**Comment by wuge0** [comment]
这注释我肯定去掉的啊
\后也没空格

**Comment by wuge0** [comment]
是后面的 \ 也去掉吗？

**Comment by wuge0** [comment]
[root@kk ~]# id root
uid=0(root) gid=0(root) groups=0(root)
[root@kk ~]# mkdir -p /dockercnf/cloudreve \
> && touch /dockercnf/cloudreve/conf.ini \
> && touch /dockercnf/cloudreve/cloudreve.db
[root@kk ~]# docker run -d \
> --name cloudreve \
> -e PUID=0 \
> -e PGID=0 \
> -e TZ="Asia/Shanghai" \
> -p 5212:5212 \
> --restart=unless-stopped \
> -v <PATH TO UPLOADS>:/cloudreve/uploads \
> -v <PATH TO conf.ini>:/cloudreve/conf.ini \
> -v <PATH TO cloudreve.db>:/cloudreve/cloudreve.db \
> -v <PATH TO avatar>:/cloudreve/avatar \
> xavierniu/cloudreve
-bash: PATH: No such file or directory
[root@kk ~]# 

重新执行还是-bash: PATH: No such file or directory

**Comment by wuge0** [comment]
![newscreen23191968](https://user-images.githubusercontent.com/31797574/125038177-b2559900-e0c7-11eb-9ef3-de8cb25bcad1.jpg)

**Comment by wuge0** [comment]
代码复制到这里就变了，你看下下图片
