### ISSUE TITLE
-bash: PATH: No such file or directory

### ISSUE THREAD

**Issue by wuge0** [xavier-niu/cloudreve-docker#43]
-bash: PATH: No such file or directory
怎么解决？
![newscreen23191968](https://user-images.githubusercontent.com/31797574/125038177-b2559900-e0c7-11eb-9ef3-de8cb25bcad1.jpg)

**Comment by justxuewei** [comment]
`<PATH TO UPLOADS>`要换成你具体的路径的，比如/sharedfolders

**Comment by wuge0** [comment]
你README.md里也没具体说明
是要创建这4个目录吗？
