### ISSUE TITLE
默认上传路径错误 & 数据无法持久化

### ISSUE THREAD

**Issue by 7th-heaven** [xavier-niu/cloudreve-docker#46]
因为cloudreve主程序放置于/bin内，而默认储存方案储存路径为 upload/.....
导致存储路径为/bin/upload。

更新容器配置会导致数据库重新初始化，已上传的文件无法在cloudreve中读取。。。（我用的是portainer，是我的姿势不对？有没有数据库重建命令？）（可能更新版本也会导致这个问题）。

**Comment by justxuewei** [comment]
感谢，目前这个问题已确认。

**Comment by justxuewei** [comment]
已修复，请使用`xavierniu/cloudreve:unstable`测试，或者等待master分支CI结束使用`latest`。
