### ISSUE TITLE
[upgrade issue] from old version, entrypoint.sh mistakenly initialized database

### ISSUE THREAD

**Issue by kmahyyg** [xavier-niu/cloudreve-docker#49]
I've correctly mounted my config file to `/cloudreve/conf.ini`  and also use `docker-compose` to start my whole application cluster.

However, after upgrade from an old version which I can't remember detailed version number, the whole container cannot start.

After analysis, the `entrypoint.sh` seems is not correctly interpreted by `/bin/bash -> /bin/sh` inside **alpine-based**.  Even the `CLOUDREVE_DEFAULT_CONF` exists, it still tries to move and create config file by using `echo` command in the sh file.

My configuration file personally configured to use MySQL as backend. So this operation will cause fatal panic to the program.

Solution:  completely rewrite the entrypoint command in your docker-compose file by using:

```yaml
entrypoint: ["cloudreve", "-c", "/cloudreve/conf.ini"]
```

You should not do those dirty works for the user. Just write a manual, let them read and fly.

**Comment by justxuewei** [comment]
Sorry for the inconvenience. The works are aimed to help users, who use SQLite as database, bump version seamlessly. However, I did not take care of all cases. The solution you mentioned looks good for me, I will update the image ASAP.

**Comment by justxuewei** [comment]
UPDATE: I've pushed the code in develop branch, you could pull the latest image with `unstable` tag once the CI is finished. Please note that the image is not tested yet, and the changes including code and docs will be available on the next release.

**Comment by kmahyyg** [comment]
The implementation in commit 1a18668 seems just solved this problem (but only for this specific situation). You should modify the README file and tell use to mount ini to correct path and make sure you've told them how to initialize and configure the application (also the SQLite database, if in use)  correctly.

**Comment by justxuewei** [comment]
Of course, this issue will not be closed until all stuff are ready.

**Comment by justxuewei** [comment]
The README is updated, and the image is tested as well. Please let me know if the bug has been fixed in the latest image. (Please wait for https://github.com/xavier-niu/cloudreve-docker/actions/runs/1153841665 to finish)
