### ISSUE TITLE
在已有ssl证书的前提下如何配置https?

### ISSUE THREAD

**Issue by scoltzero** [xavier-niu/cloudreve-docker#58]
我在nginx里输入了如下的配置

server {
  listen 80;
  listen 446 ssl;

  server_name scoltzero.top;
  ssl_certificate /etc/nginx/ssl/1_scoltzero.top_bundle.crt;
  ssl_certificate_key /etc/nginx/ssl/2_scoltzero.top.key;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:50m;
  ssl_stapling on;
  ssl_stapling_verify on;
  add_header Strict-Transport-Security max-age=15768000;
  add_header X-Frame-Options DENY;

  location / {
    proxy_pass https://www.scoltzero.top:5212;
    proxy_set_header Host $host;
  }
}

但是仍然不能启用https，不知道为什么？请问还有什么需要设定的么？

**Comment by justxuewei** [comment]
请参阅 Nginx 官方文档 [Configuring HTTPS servers](http://nginx.org/en/docs/http/configuring_https_servers.html)
