### ISSUE TITLE
请问/cloudreve/conf.ini的配置内容是什么?

### ISSUE THREAD

**Issue by fws20060501** [xavier-niu/cloudreve-docker#6]
我是windows的docker desktop运行的
运行后cloudreve工作正常

但是查看日志 会提示如下:
[Warning] 2020-04-25 11:06:58 更新检查失败, Get "https://api.github.com/repos/cloudreve/cloudreve/releases": EOF
[Warning] 2020-04-25 11:06:58 更新检查失败, unexpected end of JSON input

同时我查看/cloudreve/conf.ini 内容是空的

**Comment by justxuewei** [comment]
这种情况考虑网络连接性问题 请问你的网络环境可以访问github吗？

发自我的iPhone

**Comment by fws20060501** [comment]
> 
> 这种情况考虑网络连接性问题 请问你的网络环境可以访问github吗？ 发自我的iPhone
> […](#)
> 在 2020年4月25日，上午11:26，WinsonFang ***@***.***> 写道： ﻿ 我是windows的docker desktop运行的 运行后cloudreve工作正常 但是查看日志 会提示如下: [Warning] 2020-04-25 11:06:58 更新检查失败, Get "https://api.github.com/repos/cloudreve/cloudreve/releases": EOF [Warning] 2020-04-25 11:06:58 更新检查失败, unexpected end of JSON input 同时我查看/cloudreve/conf.ini 内容是空的 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可以的，在主机上访问https://api.github.com/repos/cloudreve/cloudreve/releases 正常，返回json

**Comment by justxuewei** [comment]
可以吧全部的log发来嘛 如果有隐私性内容可以发我邮箱

发自我的iPhone

**Comment by fws20060501** [comment]
> 
> 可以吧全部的log发来嘛 如果有隐私性内容可以发我邮箱 发自我的iPhone
> […](#)
> 在 2020年4月25日，上午11:42，WinsonFang ***@***.***> 写道： ﻿ 这种情况考虑网络连接性问题 请问你的网络环境可以访问github吗？ 发自我的iPhone … 在 2020年4月25日，上午11:26，WinsonFang @.***> 写道： ﻿ 我是windows的docker desktop运行的 运行后cloudreve工作正常 但是查看日志 会提示如下: [Warning] 2020-04-25 11:06:58 更新检查失败, Get "https://api.github.com/repos/cloudreve/cloudreve/releases": EOF [Warning] 2020-04-25 11:06:58 更新检查失败, unexpected end of JSON input 同时我查看/cloudreve/conf.ini 内容是空的 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 可以的，在主机上访问https://api.github.com/repos/cloudreve/cloudreve/releases 正常，返回json — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

全部日志信息
PS D:\docker\homecloud-compose> docker logs cloudreve

   ___ _                 _
  / __\ | ___  _   _  __| |_ __ _____   _____
 / /  | |/ _ \| | | |/ _ | '__/ _ \ \ / / _ \
/ /___| | (_) | |_| | (_| | | |  __/\ V /  __/
\____/|_|\___/ \__,_|\__,_|_|  \___| \_/ \___|

   V3.0.0  Commit #9910f8d  Pro=false
================================================

[Info]    2020-04-25 11:06:57 初始化数据库连接
[Info]    2020-04-25 11:06:57 数据库版本匹配，跳过数据库迁移
[Info]    2020-04-25 11:06:57 初始化任务队列，WorkerNum = 10
[Info]    2020-04-25 11:06:57 初始化定时任务...
[Info]    2020-04-25 11:06:57 当前运行模式：Master
[Info]    2020-04-25 11:06:57 开始监听 :5212
[Warning] 2020-04-25 11:06:58 更新检查失败, Get "https://api.github.com/repos/cloudreve/cloudreve/releases": EOF
[Warning] 2020-04-25 11:06:58 更新检查失败, unexpected end of JSON input

**Comment by justxuewei** [comment]
这个问题不是镜像的问题 运行`docker exec -it cloudreve /bin/bash`，然后运行`wget -qO- https://api.github.com/repos/cloudreve/cloudreve/releases`或者`ping api.github.com`，看看是否有输出，可能是容器内的网络不走代理造成的

**Comment by fws20060501** [comment]
> 
> 这个问题不是镜像的问题 运行 `docker exec -it cloudreve /bin/bash `，然后运行`wget -qO- [https://api.github.com/repos/cloudreve/cloudreve/releases`或者`ping](https://api.github.com/repos/cloudreve/cloudreve/releases%60%E6%88%96%E8%80%85%60ping) api.github.com`，看看是否有输出，可能是容器内的网络不走代理造成的

我把所有删除掉重新创建，那个警告就不见了，但是又出现新的问题，没提升我初始密码是什么
如何获取初始密码，非日志方式

**Comment by justxuewei** [comment]
删除配置文件夹中的cloudreve.db，删除container然后重新创建试试看
