### ISSUE TITLE
docker映射路径为空

### ISSUE THREAD

**Issue by reov** [xavier-niu/cloudreve-docker#60]
**What happened?**
将主机上的/mnt/user/映射为/cloudreve/uploads/uid/Tower，重启docker在网页上文件夹为空，但ssh命令ls可以读取到Tower文件夹内容
![image](https://user-images.githubusercontent.com/47272954/135446155-1335586c-b661-42c4-83ef-26a3938290dd.png)
![image](https://user-images.githubusercontent.com/47272954/135446251-9760d4b3-db03-40cb-a34c-55171bae45e7.png)

**What do you expect it to be?**
希望将主机内的目录挂载进cloudreve，并进行编辑移动解压等

**How to reproduce it?**
系统unraid6.9.2
`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='Cloudreve' --net='bridge' --privileged=true -e TZ="Asia/Shanghai" -e HOST_OS="Unraid" -p '5212:5212/tcp' -v '/mnt/user/App/cloudreve/uploads/':'/cloudreve/uploads':'rw' -v '/mnt/user/appdata/cloudreve/config':'/cloudreve/config':'rw' -v '/mnt/user/appdata/cloudreve/db':'/cloudreve/db':'rw' -v '/mnt/user/appdata/cloudreve/avatar':'/cloudreve/avatar':'rw' -v '/mnt/user/':'/cloudreve/uploads/1/Tower':'rw' --mount type=tmpfs,destination=/tmp 'xavierniu/cloudreve:latest'
5b14af093d81e2c15caf6b3116de662abc4241403e8aacc6de503d3b46d33010`

**Anything else?**

**Comment by justxuewei** [comment]
请问下 `/cloudreve/uploads/uid/Tower` 这个文件夹是干什么用的？在 docker 镜像中已经提供了对 `/cloudreve/uploads` 镜像的挂载点。

**Comment by reov** [comment]
这个tower文件夹是想把主机的文件目录映射到cloudreve里面，可以充当文件管理器，/cloudreve/uploads这个目录是一个总的目录，每个用户的文件只存在于/cloudreve/uploads/uid里面

**Comment by justxuewei** [comment]
你的想法不可行，因为 cloudreve 目录需要在数据库中检索，即便是挂载了也无妨使用。

**Comment by reov** [comment]
原来如此，那是不是可以放弃cloudreve了

**Comment by justxuewei** [comment]
是的，cloudreve 本意是私有网盘，而非网络目录管理器，所以可能 cloudreve 不适合你的需求。
