### ISSUE TITLE
离线下载转储存失败

### ISSUE THREAD

**Issue by cs0663c** [xavier-niu/cloudreve-docker#63]
Aria2和cloudreve都是本机docker运行链接也成功

文档中设置说明理解不了
尝试了几个方法都是提示转储失败
这里不知到是理解错误还是设置错误，请老大指点
![image](https://user-images.githubusercontent.com/59052041/143725711-d6d443b9-5459-46c8-b77b-e4647aa35d42.png)

![image](https://user-images.githubusercontent.com/59052041/143725624-c40f93ee-edcc-4b4d-ae98-ad5cea29fcb4.png)
![image](https://user-images.githubusercontent.com/59052041/143725647-b4f2e9ab-71c8-410b-aa8e-52c88bb3809d.png)

临时下载目录
Cloudreve 会指定 Aria2 将文件下载到此目录中，下载完成后 Cloudreve 会复制到指定的存储策略，并删除文件。此目录必须为绝对路径，否则 Cloudreve 在任务下载完成后会找不到文件。

**Comment by justxuewei** [comment]
你的 Aria2 的启动命令也贴一下。

**Comment by cs0663c** [comment]
> 你的 Aria2 的启动命令也贴一下。

![image](https://user-images.githubusercontent.com/59052041/143735364-86b84bb5-d2cf-48c2-983d-2f1d165339b8.png)

**Comment by justxuewei** [comment]
在你的 cloudreve 启动命令里我没看到 `-v <PATH TO temp>:/downloads` 这行。请再仔细看下文档，你的启动命令是不完整的，又怎么可能成功呢？

**Comment by cs0663c** [comment]
> 在你的 cloudreve 启动命令里我没看到 `-v <PATH TO temp>:/downloads` 这行。请再仔细看下文档，你的启动命令是不完整的，又怎么可能成功呢？

抱歉，确实没有细看文档，Aria2的下载目录也要映射temp 文件夹   cloudreve 也要temp ，我就是只映射了:/downloads 
谢谢你的回答，
