### ISSUE TITLE
仅作为从机使用，内存占用达到2.43GB

### ISSUE THREAD

**Issue by ssmnr** [xavier-niu/cloudreve-docker#65]
部署镜像后，根据官网教程配置conf.ini为从机，除此无多余操作。
然后发现，只要进行下载后，镜像内存就会狂飙到2.5GB左右，而且再也不会降下来。
手动重启镜像后，内存恢复正常到32MB左右，然后只要没有下载任务的发生，内存就会一直维持在32MB
只要发生下载，内存就会涨上去，永远不会降下来。

**Comment by justxuewei** [comment]
这个问题应该是 cloudreve 导致的，建议去 cloudreve 提交 issue。另外可以考虑不使用 docker 验证下是那边的问题。
