### ISSUE TITLE
Cloudreve的数据库文件不在db目录下

### ISSUE THREAD

**Issue by BunnySakura** [xavier-niu/cloudreve-docker#66]
**Cloudreve的数据库文件不在db目录下**

**希望修改**

**Comment by justxuewei** [comment]
请按照 issue 模版提供复现办法。

**Comment by BunnySakura** [comment]
![image](https://user-images.githubusercontent.com/48341563/144735706-f7c33da1-f780-44f7-b25f-a0fa861b7618.png)
如图参数，在docker中数据库文件并不在/cloudreve/db文件夹，而在cloudreve文件夹，故而映射到实体机的/cloudreve/db目录中不存在数据库文件

**Comment by BunnySakura** [comment]
不影响使用，但是修改数据库不方便

**Comment by justxuewei** [comment]
请问你修改 conf.ini 了吗？

**Comment by BunnySakura** [comment]
并未修改，请问如何修改？

**Comment by justxuewei** [comment]
请麻烦看下 readme。

**Comment by BunnySakura** [comment]
已解决，漏看了，感谢！！！
