### ISSUE TITLE
docker run OC方式 容器启动失败

### ISSUE THREAD

**Issue by guest6379** [xavier-niu/cloudreve-docker#7]
`docker run -d   --name cloudreve   -p 5212:5212   -v uploads:/cloudreve/uploads -v conf.ini:/cloudreve/conf.ini   -v cloudreve.db:/cloudreve/cloudreve.db   xavierniu/cloudreve`

启动失败

docker logs 

```
  ___ _                 _                    
  / __\ | ___  _   _  __| |_ __ _____   _____ 
 / /  | |/ _ \| | | |/ _ | '__/ _ \ \ / / _ \
/ /___| | (_) | |_| | (_| | | |  __/\ V /  __/
\____/|_|\___/ \__,_|\__,_|_|  \___| \_/ \___|

   V3.0.0  Commit #9910f8d  Pro=false
================================================

[Panic]   2020-05-04 20:55:03 无法解析配置文件 '/cloudreve/conf.ini': BOM: read /cloudreve/conf.ini: is a directory
panic: 无法解析配置文件 '/cloudreve/conf.ini': BOM: read /cloudreve/conf.ini: is a directory

goroutine 1 [running]:
github.com/HFO4/cloudreve/pkg/util.(*Logger).Panic(0xc000036308, 0xf0e564, 0x21, 0xc00058fbb8, 0x2, 0x2)
        /ProjectCloudreve/Cloudreve/pkg/util/logger.go:68 +0xe2
github.com/HFO4/cloudreve/pkg/conf.Init(0xc0000384a0, 0x13)
        /ProjectCloudreve/Cloudreve/pkg/conf/conf.go:110 +0x1c9
github.com/HFO4/cloudreve/bootstrap.Init(0xc0000384a0, 0x13)
        /ProjectCloudreve/Cloudreve/bootstrap/init.go:18 +0x3e
main.init.0()
        /ProjectCloudreve/Cloudreve/main.go:16 +0x120
```

**Comment by justxuewei** [comment]
你需要用touch命令预创建ini和db文件

发自我的iPhone

**Comment by guest6379** [comment]
开始报错以后，我尝试手动建立了upload目录 conf.ini和cloudreve.db文件，但还是报错。
难道我记错了？我再试试

**Comment by guest6379** [comment]
还是报错，日志如下
```
[root@helloworld d]# ls
cloudreve_3.0.0_linux_amd64.tar.gz  ok
[root@helloworld d]# touch conf.ini cloudreve.db && mkdir uploads
[root@helloworld d]# ls
cloudreve_3.0.0_linux_amd64.tar.gz  cloudreve.db  conf.ini  ok  uploads
[root@helloworld d]# docker run -d   --name cloudreve   -p 5212:5212   -v uploads:/cloudreve/uploads -v conf.ini:/cloudreve/conf.ini   -v cloudreve.db:/cloudreve/cloudreve.db   xavierniu/cloudreve
c630ac7434fd84cea22b6852392d38977d9a047f1366561efe963f093fb58662
[root@helloworld d]# docker logs cloudreve

   ___ _                 _                    
  / __\ | ___  _   _  __| |_ __ _____   _____ 
 / /  | |/ _ \| | | |/ _ | '__/ _ \ \ / / _ \
/ /___| | (_) | |_| | (_| | | |  __/\ V /  __/
\____/|_|\___/ \__,_|\__,_|_|  \___| \_/ \___|

   V3.0.0  Commit #9910f8d  Pro=false
================================================

[Panic]   2020-05-04 21:32:41 无法解析配置文件 '/cloudreve/conf.ini': BOM: read /cloudreve/conf.ini: is a directory
panic: 无法解析配置文件 '/cloudreve/conf.ini': BOM: read /cloudreve/conf.ini: is a directory

goroutine 1 [running]:
github.com/HFO4/cloudreve/pkg/util.(*Logger).Panic(0xc0001fae98, 0xf0e564, 0x21, 0xc0002adbb8, 0x2, 0x2)
        /ProjectCloudreve/Cloudreve/pkg/util/logger.go:68 +0xe2
github.com/HFO4/cloudreve/pkg/conf.Init(0xc000038620, 0x13)
        /ProjectCloudreve/Cloudreve/pkg/conf/conf.go:110 +0x1c9
github.com/HFO4/cloudreve/bootstrap.Init(0xc000038620, 0x13)
        /ProjectCloudreve/Cloudreve/bootstrap/init.go:18 +0x3e
main.init.0()
        /ProjectCloudreve/Cloudreve/main.go:16 +0x120
[root@helloworld d]# 
```

**Comment by xavier-niu** [comment]
请提供docker启动命令、touch的命令完整

**Comment by justxuewei** [comment]
> 还是报错，日志如下
> 
> ```
> [root@helloworld d]# ls
> cloudreve_3.0.0_linux_amd64.tar.gz  ok
> [root@helloworld d]# touch conf.ini cloudreve.db && mkdir uploads
> [root@helloworld d]# ls
> cloudreve_3.0.0_linux_amd64.tar.gz  cloudreve.db  conf.ini  ok  uploads
> [root@helloworld d]# docker run -d   --name cloudreve   -p 5212:5212   -v uploads:/cloudreve/uploads -v conf.ini:/cloudreve/conf.ini   -v cloudreve.db:/cloudreve/cloudreve.db   xavierniu/cloudreve
> c630ac7434fd84cea22b6852392d38977d9a047f1366561efe963f093fb58662
> [root@helloworld d]# docker logs cloudreve
> 
>    ___ _                 _                    
>   / __\ | ___  _   _  __| |_ __ _____   _____ 
>  / /  | |/ _ \| | | |/ _ | '__/ _ \ \ / / _ \
> / /___| | (_) | |_| | (_| | | |  __/\ V /  __/
> \____/|_|\___/ \__,_|\__,_|_|  \___| \_/ \___|
> 
>    V3.0.0  Commit #9910f8d  Pro=false
> ================================================
> 
> [Panic]   2020-05-04 21:32:41 无法解析配置文件 '/cloudreve/conf.ini': BOM: read /cloudreve/conf.ini: is a directory
> panic: 无法解析配置文件 '/cloudreve/conf.ini': BOM: read /cloudreve/conf.ini: is a directory
> 
> goroutine 1 [running]:
> github.com/HFO4/cloudreve/pkg/util.(*Logger).Panic(0xc0001fae98, 0xf0e564, 0x21, 0xc0002adbb8, 0x2, 0x2)
>         /ProjectCloudreve/Cloudreve/pkg/util/logger.go:68 +0xe2
> github.com/HFO4/cloudreve/pkg/conf.Init(0xc000038620, 0x13)
>         /ProjectCloudreve/Cloudreve/pkg/conf/conf.go:110 +0x1c9
> github.com/HFO4/cloudreve/bootstrap.Init(0xc000038620, 0x13)
>         /ProjectCloudreve/Cloudreve/bootstrap/init.go:18 +0x3e
> main.init.0()
>         /ProjectCloudreve/Cloudreve/main.go:16 +0x120
> [root@helloworld d]# 
> ```

我看着似乎没什么问题了，你试一试`docker rm -f cloudreve`后再试试

**Comment by justxuewei** [comment]
另外加上相对路径试一试`-v ./conf.ini:/cloudreve/conf.ini   -v ./cloudreve.db:/cloudreve/cloudreve.db`

**Comment by guest6379** [comment]
> > 还是报错，日志如下
> > ```
> > [root@helloworld d]# ls
> > cloudreve_3.0.0_linux_amd64.tar.gz  ok
> > [root@helloworld d]# touch conf.ini cloudreve.db && mkdir uploads
> > [root@helloworld d]# ls
> > cloudreve_3.0.0_linux_amd64.tar.gz  cloudreve.db  conf.ini  ok  uploads
> > [root@helloworld d]# docker run -d   --name cloudreve   -p 5212:5212   -v uploads:/cloudreve/uploads -v conf.ini:/cloudreve/conf.ini   -v cloudreve.db:/cloudreve/cloudreve.db   xavierniu/cloudreve
> > c630ac7434fd84cea22b6852392d38977d9a047f1366561efe963f093fb58662
> > [root@helloworld d]# docker logs cloudreve
> > 
> >    ___ _                 _                    
> >   / __\ | ___  _   _  __| |_ __ _____   _____ 
> >  / /  | |/ _ \| | | |/ _ | '__/ _ \ \ / / _ \
> > / /___| | (_) | |_| | (_| | | |  __/\ V /  __/
> > \____/|_|\___/ \__,_|\__,_|_|  \___| \_/ \___|
> > 
> >    V3.0.0  Commit #9910f8d  Pro=false
> > ================================================
> > 
> > [Panic]   2020-05-04 21:32:41 无法解析配置文件 '/cloudreve/conf.ini': BOM: read /cloudreve/conf.ini: is a directory
> > panic: 无法解析配置文件 '/cloudreve/conf.ini': BOM: read /cloudreve/conf.ini: is a directory
> > 
> > goroutine 1 [running]:
> > github.com/HFO4/cloudreve/pkg/util.(*Logger).Panic(0xc0001fae98, 0xf0e564, 0x21, 0xc0002adbb8, 0x2, 0x2)
> >         /ProjectCloudreve/Cloudreve/pkg/util/logger.go:68 +0xe2
> > github.com/HFO4/cloudreve/pkg/conf.Init(0xc000038620, 0x13)
> >         /ProjectCloudreve/Cloudreve/pkg/conf/conf.go:110 +0x1c9
> > github.com/HFO4/cloudreve/bootstrap.Init(0xc000038620, 0x13)
> >         /ProjectCloudreve/Cloudreve/bootstrap/init.go:18 +0x3e
> > main.init.0()
> >         /ProjectCloudreve/Cloudreve/main.go:16 +0x120
> > [root@helloworld d]# 
> > ```
> 
> 我看着似乎没什么问题了，你试一试`docker rm -f cloudreve`后再试试

上面的日志就是删除过的干净环境，不知道怎么了？
而且 docker rm -f cloudreve 以后一样报错，删了很多次了，这个是什么原因啊？

我下载cloudreve的包直接运行就是ok的

**Comment by guest6379** [comment]
是不是新版本改路径了，你docker里还用的是老路径？

**Comment by justxuewei** [comment]
并没有 你可以参考dockerfile，建议你为了防止路径错误，这一次启动全部使用**完整路径**，并**删除全部的文件和文件夹**做一次测试。

启动的方式可以参见CAC的Step5和Step6

**Comment by guest6379** [comment]
> 另外加上相对路径试一试`-v ./conf.ini:/cloudreve/conf.ini -v ./cloudreve.db:/cloudreve/cloudreve.db`

这点忽略了，马上去试试！

**Comment by guest6379** [comment]
相对路径docker会报错
ok了，在文件前面加上绝对路径。
谢谢大佬调教！
