### ISSUE TITLE
Docker:latest没有更新到3.5.0

### ISSUE THREAD

**Issue by chinachat** [xavier-niu/cloudreve-docker#74]
请作者大大尽快推送更新下。

**Comment by justxuewei** [comment]
已经更新了，请等待 github action 完成，如果想使用 3.5.0 可以考虑使用 unstable 版本。

**Comment by justxuewei** [comment]
> 已经更新了，请等待 github action 完成，如果想使用 3.5.0 可以考虑使用 unstable 版本。

UPDATE：

是这个版本 docker pull xavierniu/cloudreve:sha-6f1352d
